import { ChatMessage } from './firebaseService';

const GROQ_API_KEY = process.env.EXPO_PUBLIC_GROQ_API_KEY;
const ENDPOINT = 'https://api.groq.com/openai/v1/chat/completions';

export async function generateRegulatoryResponse(history: ChatMessage[]): Promise<string> {
  if (!GROQ_API_KEY) {
    return "Error: Missing API Key. Please add EXPO_PUBLIC_GROQ_API_KEY to your .env file and restart Expo.";
  }

  const messages = history.map((msg) => ({
    role: msg.role,
    content: msg.content
  }));

  const systemInstruction = {
    role: 'system',
    content: "You are a specialized AI Regulatory Assistant for the Jordan Investment App. Provide clear, accurate, and professional advice on Jordanian investment laws and feasibility studies."
  };

  try {
    const response = await fetch(ENDPOINT, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GROQ_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: "llama-3.1-8b-instant",
        messages: [systemInstruction, ...messages],
        temperature: 0.2, // Low temp for regulatory strictness
      })
    });

    const data = await response.json();
    
    if (data.error) {
      console.error("Groq API Error: ", data.error);
      return `API Error: ${data.error.message}`;
    }

    if (data.choices && data.choices[0]?.message?.content) {
      return data.choices[0].message.content;
    }

    return "Error: No response generated by the model.";

  } catch (error) {
    console.error("Failed to fetch from Groq:", error);
    return "Network error: Failed to connect to the AI model.";
  }
}
